import simpleGit, { SimpleGit } from 'simple-git';
import path from 'node:path';
import fs from 'node:fs';
import { slugify, computeSlugBudget, computeAutoBranchName } from '../../shared/slugify';
import { isGitRepo, isInsideWorktree, isAutoGeneratedBranch } from './git-checks';
import { linkNodeModules, removeNodeModulesPath } from './node-modules-link';
import { fetchIfStale } from './fetch-throttle';
import { removeWithRetry } from './rm-with-retry';
import { runGitWithTimeout as runGitWithTimeoutShared } from './git-spawn';

/**
 * Wall-clock ceiling for git ops in the worktree-removal path. Small repos
 * complete in <500ms, but `git worktree remove --force` on heavy node_modules
 * (observed 5-12s on real TroyWeb repos during batch retry-cleanup) needs
 * headroom. On timeout we abort the child so the per-project git queue keeps
 * moving instead of cascading.
 */
const GIT_REMOVAL_TIMEOUT_MS = 15_000;

/**
 * Wrapper that pins the (cwd, args, timeoutMs) call shape used by the
 * worktree-removal path. The shared helper accepts an optional external
 * AbortSignal that this path doesn't currently use.
 */
function runGitWithTimeout(
  projectPath: string,
  args: readonly string[],
  timeoutMs: number,
): Promise<{ stdout: string; stderr: string }> {
  return runGitWithTimeoutShared(projectPath, args, { timeoutMs });
}

/** Background prune debounce per project. */
const backgroundPruneTimestamps = new Map<string, number>();
const BACKGROUND_PRUNE_COOLDOWN_MS = 10 * 60 * 1000; // 10 minutes

// ---------------------------------------------------------------------------
// Per-project priority queue for git-mutating operations
// ---------------------------------------------------------------------------

/**
 * Priority for a queued git operation. LOWER number runs sooner, so the
 * default (USER) wins over background maintenance. A user-initiated spawn
 * enqueued behind a slow/failing background cleanup jumps ahead of every
 * other *waiting* background job - it still has to let the one currently
 * running op finish (so the `.git` lock is never contended), but it no longer
 * sits behind a pile of doomed cleanup removals.
 */
export enum GitQueuePriority {
  USER = 0,
  BACKGROUND = 10,
}

/** A single git-mutating operation waiting on (or running in) a project queue. */
interface GitJob {
  priority: number;
  /** Monotonic enqueue counter; FIFO tiebreak within equal priority. */
  seq: number;
  run: () => Promise<unknown>;
  resolve: (value: unknown) => void;
  reject: (reason: unknown) => void;
}

/**
 * Per-project scheduler state. `running` is true while exactly one job's
 * `run()` is in flight (this is what preserves the one-op-at-a-time guarantee
 * that prevents `.git` lock contention). `waiting` is kept sorted by
 * (priority asc, seq asc) so `shift()` always yields the next job to run.
 */
interface ProjectQueue {
  running: boolean;
  waiting: GitJob[];
}

const projectQueues = new Map<string, ProjectQueue>();

/** Monotonic counter for FIFO ordering within a priority band. */
let gitJobSeq = 0;

/** Normalize project path for use as a queue key (Windows is case-insensitive). */
function queueKey(projectPath: string): string {
  return process.platform === 'win32' ? projectPath.toLowerCase() : projectPath;
}

/** Options accepted by withGitLock / withLock. */
interface GitLockOptions {
  /** Lower = runs sooner. Defaults to GitQueuePriority.USER. */
  priority?: number;
  /**
   * Called synchronously at enqueue time IFF the job cannot start immediately
   * (something is running or already queued). `jobsAhead` is the number of
   * jobs that will run before this one (snapshot at enqueue; only ever an
   * upper bound as the queue drains).
   */
  onWait?: (jobsAhead: number) => void;
}

// ---------------------------------------------------------------------------
// WorktreeManager class
// ---------------------------------------------------------------------------

export class WorktreeManager {
  private git: SimpleGit;

  constructor(private projectPath: string, git?: SimpleGit) {
    this.git = git ?? simpleGit(projectPath);
  }

  /**
   * Serialize a git-mutating operation on this project's queue.
   * Only one op per project runs at a time; when the runner frees, the
   * highest-priority waiting job runs next (FIFO within equal priority).
   */
  withLock<T>(operation: () => Promise<T>, options?: GitLockOptions): Promise<T> {
    return WorktreeManager.withGitLock(this.projectPath, operation, options);
  }

  /**
   * Serialize a git-mutating operation on the given project's queue. Exactly
   * one operation runs at a time per project (no `.git` lock contention), but
   * waiting operations are ordered by priority so a user-initiated spawn does
   * not sit behind a slow/failing background cleanup. A failed operation does
   * not block subsequent ones (the runner always advances).
   */
  static withGitLock<T>(
    projectPath: string,
    operation: () => Promise<T>,
    options?: GitLockOptions,
  ): Promise<T> {
    const key = queueKey(projectPath);
    let queue = projectQueues.get(key);
    if (!queue) {
      queue = { running: false, waiting: [] };
      projectQueues.set(key, queue);
    }

    return new Promise<T>((resolve, reject) => {
      const job: GitJob = {
        priority: options?.priority ?? GitQueuePriority.USER,
        seq: gitJobSeq++,
        run: operation as () => Promise<unknown>,
        resolve: resolve as (value: unknown) => void,
        reject,
      };

      if (!queue!.running && queue!.waiting.length === 0) {
        // Runner free and nothing queued: start immediately, no wait signal.
        WorktreeManager.runJob(key, queue!, job);
        return;
      }

      // Parked behind the running op and/or other waiters. The new job always
      // has the max seq, so every equal-or-higher-priority waiter is ahead of
      // it - count them plus the running op.
      const jobsAhead = (queue!.running ? 1 : 0)
        + queue!.waiting.filter((other) => other.priority <= job.priority).length;
      WorktreeManager.insertSorted(queue!.waiting, job);
      options?.onWait?.(jobsAhead);
    });
  }

  /** Insert a job into `waiting`, keeping it sorted by (priority asc, seq asc). */
  private static insertSorted(waiting: GitJob[], job: GitJob): void {
    let insertionIndex = waiting.length;
    for (let candidateIndex = 0; candidateIndex < waiting.length; candidateIndex++) {
      if (job.priority < waiting[candidateIndex].priority
        || (job.priority === waiting[candidateIndex].priority && job.seq < waiting[candidateIndex].seq)) {
        insertionIndex = candidateIndex;
        break;
      }
    }
    waiting.splice(insertionIndex, 0, job);
  }

  /** Run a job, then drain the next waiter regardless of how this one settled. */
  private static runJob(key: string, queue: ProjectQueue, job: GitJob): void {
    queue.running = true;
    // Both arms advance the runner, so a thrown/rejected op never wedges the
    // queue (this preserves the old `previous.then(op, () => op())` behavior).
    Promise.resolve()
      .then(job.run)
      .then(
        (value) => { job.resolve(value); WorktreeManager.runNext(key); },
        (error) => { job.reject(error); WorktreeManager.runNext(key); },
      );
  }

  /** Mark the runner free and start the next-highest-priority waiting job. */
  private static runNext(key: string): void {
    const queue = projectQueues.get(key);
    // The queue may have been cleared (project closed) while a job ran; the
    // finished job simply stops and does not recreate the queue.
    if (!queue) return;
    queue.running = false;
    const next = queue.waiting.shift();
    if (next) WorktreeManager.runJob(key, queue, next);
  }

  /**
   * Remove the queue entry for a project (e.g. on project close/delete).
   * Any still-waiting jobs are rejected so their callers don't hang forever.
   * A job that is currently running is left to settle; `runNext` then finds
   * no queue entry and stops cleanly.
   */
  static clearQueue(projectPath: string): void {
    const key = queueKey(projectPath);
    const queue = projectQueues.get(key);
    if (queue) {
      for (const job of queue.waiting) {
        job.reject(new Error('Git queue cleared (project closed)'));
      }
      queue.waiting.length = 0;
    }
    projectQueues.delete(key);
  }

  /**
   * Guard + create worktree in one call. Returns null if any guard fails
   * (already has worktree, worktrees disabled, not a git repo, is a worktree).
   */
  async ensureWorktree(
    task: { id: string; title: string; worktree_path: string | null; branch_name?: string | null; base_branch?: string | null; use_worktree?: number | null },
    gitConfig: { worktreesEnabled: boolean; defaultBaseBranch: string; copyFiles: string[] },
    options?: { onProgress?: (phase: string) => void; signal?: AbortSignal },
  ): Promise<{ worktreePath: string; branchName: string } | null> {
    if (task.worktree_path) return null;
    const shouldUseWorktree = task.use_worktree != null
      ? Boolean(task.use_worktree)
      : gitConfig.worktreesEnabled;
    if (!shouldUseWorktree) return null;
    if (!isGitRepo(this.projectPath)) return null;
    if (isInsideWorktree(this.projectPath)) return null;

    const defaultBaseBranch = gitConfig.defaultBaseBranch || 'main';
    const baseBranch = task.base_branch || defaultBaseBranch;
    return this.createWorktree(task.id, task.title, baseBranch, gitConfig.copyFiles, task.branch_name, { onProgress: options?.onProgress, signal: options?.signal, defaultBaseBranch });
  }

  /**
   * Create a worktree for a task. The worktree folder and branch are named
   * using a slug derived from the task title, with the taskId suffix to
   * guarantee uniqueness.
   *
   * Callers must wrap with `withLock()` to serialize concurrent operations
   * on the same project and prevent git lock contention.
   */
  async createWorktree(
    taskId: string,
    taskTitle: string,
    baseBranch: string = 'main',
    copyFiles: string[] = [],
    customBranchName?: string | null,
    options?: { onProgress?: (phase: string) => void; signal?: AbortSignal; defaultBaseBranch?: string },
  ): Promise<{ worktreePath: string; branchName: string }> {
    const shortId = taskId.slice(0, 8);
    const defaultBaseBranch = options?.defaultBaseBranch ?? 'main';
    let branchName: string;
    let folderName: string;

    // On Windows, dynamically compute slug length to stay under MAX_PATH (260).
    // On other platforms, use the static default (20 chars).
    const slugBudget = process.platform === 'win32'
      ? computeSlugBudget(this.projectPath)
      : 20;

    if (customBranchName) {
      branchName = customBranchName;
      // Folder naming MUST be stable across a Done round-trip. Claude keys its
      // transcript by the cwd (~/.claude/projects/<slug-of-cwd>/<id>.jsonl), so
      // if the recreated worktree lands at a different path than the original
      // session ran in, `--resume <id>` looks under the wrong slug, reports
      // "No conversation found", and the (still-on-disk) session is lost.
      //
      // On move-out-of-Done the preserved branch_name is passed back here as
      // customBranchName. For our own AUTO-generated branches that name already
      // ends in `-<shortId>`, so re-slugifying it and appending shortId again
      // doubles the suffix (dns-setup-4e41b16b -> dns-setup-4e41b16b-4e41b16b)
      // and changes the cwd. Derive the folder from the TITLE instead, exactly
      // as the first creation did, so the path is reproduced verbatim. Only
      // genuinely custom user branches (which never embed the shortId suffix)
      // stay branch-derived - those are already stable across round-trips, and
      // re-deriving them would orphan their existing transcripts.
      if (isAutoGeneratedBranch(customBranchName, taskId, taskTitle)) {
        folderName = `${slugify(taskTitle, slugBudget) || 'task'}-${shortId}`;
      } else {
        // Slugify the custom name for the folder (replace / with -)
        const slugifiedCustom = slugify(customBranchName.replace(/\//g, '-'), slugBudget);
        folderName = `${slugifiedCustom || 'task'}-${shortId}`;
      }
    } else {
      const slug = slugify(taskTitle, slugBudget) || 'task';
      folderName = `${slug}-${shortId}`;
      // Branch name may include a base-branch namespace prefix when branching
      // off a non-default base; folder name intentionally stays flat.
      branchName = computeAutoBranchName(baseBranch, defaultBaseBranch, slug, shortId);
    }

    const worktreePath = path.join(this.projectPath, '.kangentic', 'worktrees', folderName);

    // Ensure worktrees dir exists
    const worktreesDir = path.join(this.projectPath, '.kangentic', 'worktrees');
    try {
      await fs.promises.mkdir(worktreesDir, { recursive: true });
    } catch (err) {
      console.error(`[WORKTREE] Failed to create worktrees directory: ${worktreesDir}`, err);
      throw new Error(`Cannot create worktrees directory at ${worktreesDir}: ${(err as Error).message}`);
    }

    // Fetch the latest from origin so worktrees start from up-to-date code.
    // Uses throttle cache to skip redundant fetches within a 5-minute window.
    // Emit 'fetching' here (not eagerly before the lock) so a job that parked
    // in the queue flips from "Waiting for git queue..." to "Fetching latest..."
    // the instant it actually starts the fetch.
    options?.onProgress?.('fetching');
    const startPoint = await fetchIfStale(this.git, this.projectPath, baseBranch, { signal: options?.signal });
    options?.onProgress?.('creating-worktree');
    options?.signal?.throwIfAborted();

    // Check if the branch already exists (stale branch from failed cleanup,
    // or pre-existing custom branch)
    let branchExists = false;
    try {
      await this.git.raw(['rev-parse', '--verify', branchName]);
      branchExists = true;
    } catch {
      // Branch does not exist -- will create it
    }
    options?.signal?.throwIfAborted();

    // Create worktree: attach to existing branch or create a new one.
    // Callers must wrap with withLock() to serialize concurrent operations.
    // Use full removeWorktree (git worktree remove --force + EPERM retries)
    // instead of a single rmSync. On Windows, file handles from a recently
    // killed PTY may still be held, and rmSync fails with EPERM.
    if (fs.existsSync(worktreePath)) {
      const removed = await this.removeWorktree(worktreePath);
      if (!removed) {
        throw new Error(`Cannot create worktree: stale directory at ${worktreePath} could not be removed. A process may still hold file handles. Close any terminals or editors using this path and retry.`);
      }
      options?.signal?.throwIfAborted();
    }
    // On Windows, enable long paths to prevent "Filename too long" errors
    // when the project contains deeply nested files (e.g. .NET migrations).
    // The -c flag is per-command and does not modify the project's git config.
    // This setting is Windows-only (uses \\?\ extended-length path prefix);
    // macOS/Linux have 1024-4096 byte PATH_MAX and are unaffected.
    const longPathsConfig = process.platform === 'win32' ? ['-c', 'core.longpaths=true'] : [];
    if (branchExists) {
      await this.git.raw([...longPathsConfig, 'worktree', 'add', worktreePath, branchName]);
      console.log(`[WORKTREE] Created worktree (existing branch): ${branchName}`);
    } else {
      await this.git.raw([...longPathsConfig, 'worktree', 'add', '-b', branchName, worktreePath, startPoint]);
      console.log(`[WORKTREE] Created worktree (new branch): ${branchName} from ${startPoint}`);
    }

    // Post-creation configuration: these steps all write to the new
    // worktree's `.git/config` (base-branch key, Windows longpaths, and
    // sparse-checkout's `extensions.worktreeConfig`). They were previously
    // wrapped in Promise.all under the assumption they touched independent
    // parts of the .git state - but on Windows concurrent writes to the same
    // config file intermittently race on the lock ("could not lock config
    // file... File exists"), silently swallowing sparse-checkout init and
    // leaving `.claude/commands/` materialized. Serial execution costs a
    // handful of milliseconds and eliminates the race.
    const wtGit = simpleGit(worktreePath);

    // Store the base branch in git config so agents can read it via
    // `git config kangentic.baseBranch` without accessing files outside the worktree.
    try {
      await wtGit.raw(['config', 'kangentic.baseBranch', baseBranch]);
    } catch {
      // Non-fatal -- merge-back falls back to 'main'
    }

    // Persist long paths in the worktree's local config (Windows only).
    if (process.platform === 'win32') {
      try {
        await wtGit.raw(['config', 'core.longpaths', 'true']);
      } catch {
        // non-fatal
      }
    }

    // Exclude .claude/commands/ from worktree via sparse-checkout.
    // Commands walk up the directory tree from worktree CWD to the main repo's
    // .claude/commands/, so excluding them prevents duplicate discovery.
    // Requires git 2.25+; older versions skip gracefully.
    try {
      await wtGit.raw(['sparse-checkout', 'init', '--no-cone']);
      await wtGit.raw(['sparse-checkout', 'set', '/*', '!/.claude/commands/']);
    } catch (sparseError) {
      console.warn('[WORKTREE] Sparse-checkout not available (requires git 2.25+), skipping:', sparseError);
    }

    // Copy specified files into the worktree (skip .claude/ entries --
    // sparse-checkout keeps .claude/ but excludes commands/,
    // and hooks are delivered via --settings flag pointing to session directory).
    // Async fs so the per-file copy loop yields the event loop between files
    // instead of blocking it: a busy main process otherwise bunches the spawn
    // progress IPC pushes, which then land as one burst on the renderer.
    for (const file of copyFiles) {
      if (file.startsWith('.claude/') || file.startsWith('.claude\\')) continue;
      const src = path.join(this.projectPath, file);
      const dest = path.join(worktreePath, file);
      try {
        await fs.promises.access(src);
      } catch {
        continue; // Source does not exist -- nothing to copy.
      }
      await fs.promises.mkdir(path.dirname(dest), { recursive: true });
      await fs.promises.copyFile(src, dest);
    }

    // Link node_modules from root so worktree agents can run typecheck/test
    // without a slow npm install. Non-fatal if it fails.
    await linkNodeModules(worktreePath, this.projectPath);

    return { worktreePath, branchName };
  }

  /**
   * Rename the git branch for a task after a title edit.
   * Only renames the branch ref -- the worktree directory stays unchanged.
   * Returns the new branch name on success, null if skipped or failed.
   */
  async renameBranch(
    taskId: string,
    oldBranchName: string,
    newTitle: string,
    options?: { baseBranch?: string | null; defaultBaseBranch?: string },
  ): Promise<string | null> {
    const slugBudget = process.platform === 'win32'
      ? computeSlugBudget(this.projectPath)
      : 20;
    const slug = slugify(newTitle, slugBudget) || 'task';
    const shortId = taskId.slice(0, 8);
    const baseBranch = options?.baseBranch ?? '';
    const defaultBaseBranch = options?.defaultBaseBranch ?? 'main';
    const newBranchName = computeAutoBranchName(baseBranch, defaultBaseBranch, slug, shortId);

    if (newBranchName === oldBranchName) return null; // slug didn't change

    try {
      await this.git.raw(['branch', '-m', oldBranchName, newBranchName]);
      return newBranchName;
    } catch (err) {
      console.error('[WORKTREE] Branch rename failed:', err);
      return null;
    }
  }

  /**
   * Remove a worktree directory. Returns false when the directory could not be
   * removed (file handles still held) so the caller leaves `worktree_path` set
   * for the next project-open retry pass.
   *
   * `options.timeoutMs` caps each git call; `options.fast` short-circuits the
   * manual-removal backoff to a single attempt. Background retry cleanup passes
   * both (it is best-effort and deferred to next open anyway) so it cannot hold
   * the per-project git queue for the full 15s while a user spawn waits behind
   * it. The user-initiated create path passes no options and keeps the full
   * timeout + backoff.
   */
  async removeWorktree(
    worktreePath: string,
    options?: { timeoutMs?: number; fast?: boolean },
  ): Promise<boolean> {
    if (!fs.existsSync(worktreePath)) return true;

    const timeoutMs = options?.timeoutMs ?? GIT_REMOVAL_TIMEOUT_MS;

    // Remove node_modules junction BEFORE any recursive operation to prevent
    // git worktree remove (or the async rm below) from traversing the junction
    // and deleting the main repo's node_modules. Async so a real (non-junction)
    // node_modules with many files doesn't block the main-process event loop.
    await removeNodeModulesPath(path.join(worktreePath, 'node_modules'));

    try {
      await runGitWithTimeout(
        this.projectPath,
        ['worktree', 'remove', worktreePath, '--force'],
        timeoutMs,
      );
      return true;
    } catch (error) {
      console.log(`[WORKTREE] git worktree remove failed, falling back to manual removal: ${(error as Error).message}`);
    }

    // Stat-first recursive removal with exponential backoff (0/100/500/2000ms).
    // Windows NTFS transient locks (EBUSY, ENOTEMPTY, EPERM) on .git/objects/pack/*
    // and lingering child-process handles need longer than the old 2s window.
    // Also handles EISDIR explicitly (dirent race where a child flips from
    // file to directory mid-walk), which Node's recursive rm can surface on
    // nested node_modules left by sub-package npm installs.
    //
    // Fast mode (background retry) collapses both the outer backoff AND Node's
    // inner fs.rm retries to a single attempt, so the whole call is bounded by
    // `timeoutMs` rather than ~15s + ~3.7s backoff + ~2s inner retry.
    try {
      await removeWithRetry(worktreePath, options?.fast ? { delays: [0], innerMaxRetries: 0 } : undefined);
      await runGitWithTimeout(this.projectPath, ['worktree', 'prune'], timeoutMs);
      return true;
    } catch (error) {
      const err = error as NodeJS.ErrnoException;
      console.warn(
        `[WorktreeManager] Could not remove worktree after retries: ${worktreePath} `
        + `(code=${err.code ?? 'unknown'} errno=${err.errno ?? '?'} syscall=${err.syscall ?? '?'} path=${err.path ?? '?'}): ${err.message}`
      );
      // Best-effort prune so git's worktree metadata is consistent even when
      // the directory itself couldn't be removed. The task.worktree_path
      // stays set so the next project open's retry pass can try again once
      // whatever was holding file handles (orphaned subprocesses, AV scan)
      // has moved on.
      try {
        await runGitWithTimeout(this.projectPath, ['worktree', 'prune'], timeoutMs);
      } catch { /* best effort */ }
      return false;
    }
  }

  async removeBranch(branchName: string): Promise<void> {
    try {
      await runGitWithTimeout(this.projectPath, ['branch', '-D', branchName], GIT_REMOVAL_TIMEOUT_MS);
    } catch { /* branch may not exist, or git hung and was killed */ }
  }

  /**
   * List remote branches sorted by most recent commit first.
   * Fetches from origin first (fails silently if offline).
   */
  async listRemoteBranches(): Promise<string[]> {
    try { await this.git.raw(['fetch', '--prune']); } catch { /* offline OK */ }
    // %(refname:short) shortens origin/HEAD to bare "origin" -- filter by
    // requiring the origin/ prefix before stripping it, which excludes both
    // the HEAD symref and any non-origin remotes.
    const raw = await this.git.raw(['branch', '-r', '--sort=-committerdate', '--format=%(refname:short)']);
    const seen = new Set<string>();
    return raw.split('\n')
      .map(l => l.trim())
      .filter(l => l.startsWith('origin/') && !l.endsWith('/HEAD'))
      .map(l => l.slice('origin/'.length))
      .filter(l => {
        if (!l || seen.has(l)) return false;
        seen.add(l);
        return true;
      });
  }

  /**
   * Checkout a branch in the main repo for non-worktree tasks.
   * Throws if the working tree is dirty or the branch doesn't exist.
   */
  async checkoutBranch(branchName: string): Promise<void> {
    const currentBranch = (await this.git.revparse(['--abbrev-ref', 'HEAD'])).trim();
    if (currentBranch === branchName) return;

    const status = await this.git.status();
    const trackedChanges = status.files.filter(
      file => file.index !== '?' && file.working_dir !== '?',
    );
    if (trackedChanges.length > 0) {
      throw new Error(
        `Cannot switch to branch '${branchName}': you have uncommitted changes. `
        + `Commit or stash your changes, or enable worktree mode for this task.`
      );
    }

    await this.git.checkout(branchName);
  }

  async pruneWorktrees(): Promise<void> {
    await runGitWithTimeout(this.projectPath, ['worktree', 'prune'], GIT_REMOVAL_TIMEOUT_MS);
  }

  /**
   * Schedule a background prune for this project. Debounced per-project
   * (at most once per 10 minutes). Acquires the git lock to avoid
   * contention with concurrent worktree operations. Never throws.
   */
  static scheduleBackgroundPrune(projectPath: string): void {
    const key = process.platform === 'win32' ? projectPath.toLowerCase() : projectPath;
    const lastPrune = backgroundPruneTimestamps.get(key);
    if (lastPrune && Date.now() - lastPrune < BACKGROUND_PRUNE_COOLDOWN_MS) return;
    backgroundPruneTimestamps.set(key, Date.now());

    WorktreeManager.withGitLock(projectPath, async () => {
      // Bounded git call (matches pruneWorktrees): an unbounded simple-git
      // prune that hangs on a held .git lock would set queue.running and never
      // release, wedging every later op (incl. user spawns) on this project.
      await runGitWithTimeout(projectPath, ['worktree', 'prune'], GIT_REMOVAL_TIMEOUT_MS);
      console.log(`[WORKTREE] Background prune completed for ${projectPath}`);
    }, { priority: GitQueuePriority.BACKGROUND }).catch((error) => {
      console.warn(`[WORKTREE] Background prune failed (non-fatal): ${(error as Error).message}`);
    });
  }

  async listWorktrees(): Promise<string[]> {
    const result = await this.git.raw(['worktree', 'list', '--porcelain']);
    const worktrees: string[] = [];
    for (const line of result.split('\n')) {
      if (line.startsWith('worktree ')) {
        worktrees.push(line.replace('worktree ', ''));
      }
    }
    return worktrees;
  }

}
